
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
struct Buy
{
    uint id;
    string name;
    uint count;
    uint addTime;
    bool bought;
    uint buyPrice;
}